### ISSUE TITLE
Fichier Main.axml inexistant

### ISSUE THREAD

**Issue by Developwebpro** [MicrosoftDocs/xamarin-docs.fr-fr#11]
Bonjour,
Je me permet de mettre un commentaire pour vous signaler que le fichier Main.axml n'existe pas dans un projet Xamarin.
Je ne possède que 2 fichiers .axml dans le dossier layout : Tabbar.axml et Toolbar.axml mais pas Main.axml.
Comment faire pour régler ce problème ?
Merci
Cordialement
Developwebpro

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ec0bffcf-533c-d84b-dcf1-241758a7d217
* Version Independent ID: 27840f5e-7b18-6a10-547d-1dc53dfe90f2
* Content: [RatingBar - Xamarin](https://docs.microsoft.com/fr-fr/xamarin/android/user-interface/controls/ratingbar#feedback)
* Content Source: [docs/android/user-interface/controls/ratingbar.md](https://github.com/MicrosoftDocs/xamarin-docs.fr-FR/blob/live/docs/android/user-interface/controls/ratingbar.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Bonjour @Developwebpro 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by conceptdev** [comment]
**Xamarin.Forms - Android** projects contain Tabbar.axml & Toolbar.axml. 

**Xamarin.Android** project type contains Main.axml (Windows) or activity_main.axml (Mac). 

[RatingBar](https://docs.microsoft.com/fr-fr/xamarin/android/user-interface/controls/ratingbar) is for **Xamarin.Android**.

**Comment by Developwebpro** [comment]
Hello, so if I understand correctly, it is not possible to make an RatingBar with Xamarin.Forms but only with Xamarin.Android.  Is there an alternative to the RatingBar?  If yes, how ?  Thanks for your help.

**Comment by Developwebpro** [comment]
Hello, so if I understand correctly, it is not possible to make an RatingBar with Xamarin.Forms but only with Xamarin.Android.  Is there an alternative to the RatingBar with Xamarin.Forms ?  If yes, how ?  Thanks for your help.

**Comment by conceptdev** [comment]
Correct, there is no built-in RatingBar control for Xamarin.Forms - the available controls are [listed here](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/controls/views).

I found a match on the SyncFusion site https://www.syncfusion.com/xamarin-ui-controls/xamarin-rating

**Comment by Developwebpro** [comment]
Thank you very much. I will work on it and keep you informed of the progress of my project.
