### ISSUE TITLE
Erreur de grammaire "Cette exemple"

### ISSUE THREAD

**Issue by bruno-bmlp** [MicrosoftDocs/xamarin-docs.fr-fr#12]
Erreur dans la phrase suivante : "La section suivante illustre **cette** exemple"
La phrase correcte est : "La section suivante illustre **cet** exemple"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ba4ac72b-0c09-80b8-7210-c77f1d2a6f42
* Version Independent ID: f39106cc-ec1f-55ea-002a-8928e742b551
* Content: [Hello, Android - En profondeur - Xamarin](https://docs.microsoft.com/fr-fr/xamarin/android/get-started/hello-android/hello-android-deepdive)
* Content Source: [docs/android/get-started/hello-android/hello-android-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs.fr-fr/blob/live/docs/android/get-started/hello-android/hello-android-deepdive.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @bruno-bmlp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Bonjour @bruno-bmlp , 

Merci pour votre contribution. 

Les contributions relatives aux problèmes de traduction dans le contenu traduit automatiquement ne sont actuellement pas acceptées. 

Nous apprécions vos contributions et suggestions au contenu issu de la traduction humaine, qui sont utilisées pour effectuer l’apprentissage des moteurs de traduction automatique. Vos contributions amélioreront ainsi la qualité des traductions humaine et machine. 

Pour distinguer les rubriques traduites manuellement de celles traduites automatiquement, référez-vous à la valeur de métadonnées ms.translationtype qui figure dans l’en-tête de chaque fichier de contenu : "HT" fait référence à la traduction humaine et "MT" à la traduction machine. 

Un grand merci pour votre aide. 
L’équipe Microsoft DOCS Global Experience
