### ISSUE TITLE
Améliorer la traduction/Improve the translation

### ISSUE THREAD

**Issue by Eurkainis** [MicrosoftDocs/xamarin-docs.fr-fr#3]
Bonjour, la traduction sur les chapitres à partir de XAML n'est plus compréhensible pour un non anglophone, merci de revoir cela.
Hello, the translation from XAML chapter is not understandable for a non English speaker, could you improve that.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f9c4a77e-2256-cfe7-42b2-63041b588b68
* Version Independent ID: 5ade4bab-b189-eeeb-b8c8-1f6546d287d5
* Content: [Classe d’application Xamarin.Forms - Xamarin](https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/app-fundamentals/application-class)
* Content Source: [docs/xamarin-forms/app-fundamentals/application-class.md](https://github.com/MicrosoftDocs/xamarin-docs.fr-FR/blob/live/docs/xamarin-forms/app-fundamentals/application-class.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by LisandroSu** [comment]
Hello, @Eurkainis , 
 
Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" ("Lire en anglais") option on the right which allows you to switch to the English version without having to change the language settings. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LeBzul** [comment]
Hello @LisandroSu 
Qu'elle est l'utilité de laisser les documentations en Fr, si celle-ci sont totalement incompréhensibles et qu'on est obligé de passer en anglais ?
