### ISSUE TITLE
documentation compatibility visual studio 2017

### ISSUE THREAD

**Issue by bigbrownies** [MicrosoftDocs/xamarin-docs.fr-fr#4]
Hi,

I try to use this extension on visual studio 2017 on Windows 10.
But the first step can't be found in my IDE.

Best regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bc761a74-1771-ba79-bb12-dafbf36cbba2
* Version Independent ID: f2b83e12-5230-d075-56bc-48af44747c96
* Content: [Création d’un NuGet à partir de projets de bibliothèque existant - Xamarin](https://docs.microsoft.com/fr-fr/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/existing-library)
* Content Source: [docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/existing-library.md](https://github.com/MicrosoftDocs/xamarin-docs.fr-FR/blob/live/docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/existing-library.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by LisandroSu** [comment]
Hello, @bigbrownies 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
