### ISSUE TITLE
Xamarin Live Player Visualization error

### ISSUE THREAD

**Issue by pldeschamps** [MicrosoftDocs/xamarin-docs.fr-fr#8]
Xamarin Live Player did never work.

VS community 2017 Version 15.9.4
Live Player Version 1.5.241 (741)

In IDE :
Built with 0 message
Deploy to HUAWEI ANE-LX1 Player succeded

In Live Player:
Visualization Error
Assembly must be a runtime Assembly object.
(ArgumentException)

An Idea how to solve this problem?
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 07cbe485-3d3b-c8e0-410e-3d04e1beb269
* Version Independent ID: ec2a19ac-ce29-8644-70c1-4a3becb5cda4
* Content: [Xamarin Live Player pour Xamarin.Forms - Xamarin](https://docs.microsoft.com/fr-fr/xamarin/tools/live-player/#troubleshootingtroubleshootingmd)
* Content Source: [docs/tools/live-player/index.md](https://github.com/MicrosoftDocs/xamarin-docs.fr-FR/blob/live/docs/tools/live-player/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by CeciAc** [comment]
Hello, @pldeschamps 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
