### ISSUE TITLE
Handle Conflicts with Plugin.Permission

### ISSUE THREAD

**Issue by BenjaminSAILcloud** [MicrosoftDocs/xamarin-docs.fr-fr#9]
I have an app that uses Geolocator implementation with the StartListeningAsync service. But Geolocator uses the permission plugin which also need me to override the OnRequestPermissionsResult method. If I want to use one service of Xamarin.Essentials, how do I make the plugins coexist ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Bien démarrer avec Xamarin.Essentials - Xamarin](https://docs.microsoft.com/fr-fr/xamarin/essentials/get-started?context=xamarin%2Fxamarin-forms&tabs=windows%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs.fr-FR/blob/live/docs/essentials/get-started.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by CeciAc** [comment]
Hello, @BenjaminSAILcloud 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by BenjaminSAILcloud** [comment]
Thanks for your answer.

I did found the anwser in the xamarin/Essentials/issues/335 issue.
